### ISSUE TITLE
Allow a ProjectController's _fallbackProvider to be set after deployment

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/upgradeability-lib#37]
Atm, `_fallbackProvider` can only be set in the constructor. If a user deployed a project controller with no fallback provider, and then decided to add one in order to access zos implementations, she would have to throw the ProjectController away and set up a completely new one.

If changing a provider once set is a controversial operation, we could consider allowing to set the provider only if the current one is not `0x0`.

**Comment by frangio** [comment]
Consider providing the same feature for the registry.
